//! The licence window: SimLogix's own terms, and those of everything it is
//! built on.
//!
//! # Why the text is embedded rather than read from disk
//!
//! The obligation these licences carry is attribution, and attribution has to
//! reach whoever ends up with a copy. A file sitting next to the binary is
//! one that can be separated from it; text compiled *into* the binary cannot
//! be. `THIRD-PARTY.md` is generated by the `write-licenses` tool and checked
//! in, so it is also readable without running anything.
//!
//! # Why it is drawn line by line
//!
//! The third-party notice is some 700 KiB. Handing that to egui as one label
//! would lay out every line of it on every frame; [`egui::ScrollArea`]'s
//! row-range form lays out only what is on screen. That is the whole reason
//! the text is split once and cached.

use std::sync::OnceLock;

use egui::{Context, Ui};

use crate::i18n::Strings;

/// SimLogix's own terms — the same file the repository ships, so the two
/// cannot come to disagree.
const OWN: &str = include_str!("../../LICENSE");

/// Generated by `cargo run -p simlogix-gui --bin write-licenses`.
const THIRD_PARTY: &str = include_str!("../../THIRD-PARTY.md");

/// Which half of the window is showing.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub enum Tab {
    #[default]
    Own,
    ThirdParty,
}

/// Split once for the lifetime of the process, not once per frame.
fn lines(text: &'static str) -> &'static [&'static str] {
    static OWN_LINES: OnceLock<Vec<&'static str>> = OnceLock::new();
    static THIRD_LINES: OnceLock<Vec<&'static str>> = OnceLock::new();
    let cell = if std::ptr::eq(text, OWN) {
        &OWN_LINES
    } else {
        &THIRD_LINES
    };
    cell.get_or_init(|| text.lines().collect())
}

/// Draws the window while `open`, and lets its close button clear the flag.
pub fn show(ctx: &Context, strings: &Strings, open: &mut bool, tab: &mut Tab) {
    egui::Window::new(strings.licenses_title)
        .open(open)
        .collapsible(false)
        .resizable(true)
        .default_width(620.0)
        .default_height(460.0)
        .show(ctx, |ui| body(ui, strings, tab));
}

fn body(ui: &mut Ui, strings: &Strings, tab: &mut Tab) {
    ui.horizontal(|ui| {
        for (option, label) in [
            (Tab::Own, strings.licenses_own),
            (Tab::ThirdParty, strings.licenses_third_party),
        ] {
            if ui.selectable_label(*tab == option, label).clicked() {
                *tab = option;
            }
        }
    });
    ui.separator();

    let text = match tab {
        Tab::Own => OWN,
        Tab::ThirdParty => {
            // Said up front, because a 421-entry list looks like a problem
            // until you know it is only an acknowledgement.
            ui.label(strings.licenses_third_party_intro);
            ui.add_space(4.0);
            THIRD_PARTY
        }
    };

    let rows = lines(text);
    let row_height = ui.text_style_height(&egui::TextStyle::Monospace);
    egui::ScrollArea::both()
        .auto_shrink([false, false])
        .show_rows(ui, row_height, rows.len(), |ui, range| {
            for line in &rows[range] {
                // Monospace throughout: these are licence texts, and their
                // own line breaks are the layout they were written with.
                ui.label(egui::RichText::new(*line).monospace());
            }
        });
}

// -----------------------------------------------------------------------------
// Tests
// -----------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_licence_is_the_one_the_repository_ships() {
        // `include_str!` makes this true by construction; the test is here so
        // that emptying or renaming the file fails loudly rather than
        // shipping a window with nothing in it.
        assert!(OWN.contains("MIT License"));
        assert!(OWN.contains("Romain VOLPI"));
        assert!(OWN.contains("without restriction"));
    }

    #[test]
    fn the_third_party_notice_is_generated_and_not_empty() {
        assert!(THIRD_PARTY.contains("## Dependencies"));
        assert!(THIRD_PARTY.contains("## Licence texts"));
        // A regenerated file that lost its dependencies would still contain
        // the headings, so check there is a table under them.
        assert!(THIRD_PARTY.matches("\n| ").count() > 50);
    }

    #[test]
    fn every_dependency_declares_a_licence() {
        // The generator writes this marker rather than guessing. One
        // appearing means a dependency arrived with no terms attached, which
        // is a decision to make and not a line to scroll past.
        assert!(
            !THIRD_PARTY.contains("NOT DECLARED"),
            "a dependency ships without a declared licence"
        );
    }

    #[test]
    fn both_tabs_have_something_to_show() {
        for text in [OWN, THIRD_PARTY] {
            assert!(!lines(text).is_empty());
        }
    }
}
